### ISSUE TITLE
Todo to fix styles / layout for high fidelity to superformula.com

### ISSUE THREAD

**Issue by syntapy** [syntapy/superformula_clone#73]
Right now my rendition looks like *shit*. To fix that I need

- [x] No underlines in header nav
- [ ] Redo mobile nav header
- [ ] Outline around buttons
- [ ] Redo title header contents according to their new style
  - [ ] Colorized 3rd word
- [ ] Correct font sizes in text
- [ ] Correct font styles in text
- [ ] Recent case studies section
   - [ ] grab drag in mobile

**Comment by syntapy** [comment]
Gonna use a milestone instead
